apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tbspsp:privileged
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - POD_SECURITY_POLICY_NAME
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tbs:psp:privileged
roleRef:
  kind: ClusterRole
  name: tbspsp:privileged
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: system:serviceaccounts
  apiGroup: rbac.authorization.k8s.io